### ISSUE TITLE
调用hide方法后，进行地图缩放等操作，隐藏的实例又出现了

### ISSUE THREAD

**Issue by GitHumburger** [lin-123/leaflet.migration#44]
https://codesandbox.io/s/determined-satoshi-dz9qtn?file=/App.jsx
必现

**Comment by GitHumburger** [comment]
> https://codesandbox.io/s/determined-satoshi-dz9qtn?file=/App.jsx 必现

就在你的demo基础上改的，点击rendomData后，缩放地图既能复现

**Comment by lin-123** [comment]
@GitHumburger  可能是内部有些单例的实现没处理好，有时间可以看下

**Comment by lin-123** [comment]
请参考这个实例 https://lin-123.github.io/leaflet.migration/multi-instance
